### ISSUE TITLE
Integration question

### ISSUE THREAD

**Issue by stickybombz** [Santagain/DBG_LesterJobs#1]
How would i integrate this so that you must have a job from lester to be able to access the drugs in the server. I have more than just meth weed and coke, and am at a loss at how to code this

**Comment by DioneB** [comment]
this plugin is just to list the dirty jobs, how esx_job_listing works, but without mixing the 2, to make a dirty job appear in the list just add the job to the database in the jobs table, and set the LesterJob column to 1 , then the profession will be listed there, remember to define the column Whitelisted as 1 also, not to appear in the  job agency
EX:

INSERT INTO `jobs` (`id`, `name`, `label`, `whitelisted`, `LesterJob`) VALUES (NULL, 'hacker', 'Hacker', '1', '1')

**Comment by DioneB** [comment]
if you want to block the jobs to work only with the profession you must do a check before running your code
EX:

--[Client Example]
if PlayerData.job ~= nil and PlayerData.job.name == 'meth_dealer' then
-- YOUR CODE
end
